# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sisitts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sisit',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 14, 35, 37, 22271, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
