# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisitts', '0003_auto_20170725_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sisit',
            old_name='likes',
            new_name='likes_count',
        ),
    ]
