# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sisitts', '0004_auto_20170725_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='sisit',
            name='likes',
            field=models.ManyToManyField(related_name='liked_sisits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sisit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_sisits', to=settings.AUTH_USER_MODEL),
        ),
    ]
